let num1: number = 4;
let num2: number = 4;
console.log(num1 + num2);
let num3: number = 4;
let num4: number = 2;
console.log(num3*num4);
let num5: number = 16;
let num6: number = 2;
console.log(num5/num6);
let num7: number = 16;
let num8: number = 8;
console.log(num7-num8);